server:
  port: 8081

spring:
  datasource:
    url: jdbc:oracle:thin:@//localhost:1522/ORCLPDB
    username: artist
    password: artist123
    driver-class-name: oracle.jdbc.OracleDriver

  devtools:
    restart:
      enabled: true

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: always

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
